# Gradle JVM args
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=false

# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true

# Suppress warning AGP 8.2.0 vs compileSdk 35
android.suppressUnsupportedCompileSdk=35

# Kotlin
kotlin.code.style=official
